/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tampilandatabase;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author ASUS
 */
public class TampilanGUIku extends javax.swing.JFrame {

    public void peringatan(String pesan) {
        JOptionPane.showMessageDialog(rootPane, pesan);
    }
    ArrayList<Guru> dataGuru;

    private int masukkanData(Connection conn, String ID_Guru, String Nama, String Mata_Pelajaran) throws SQLException {
        PreparedStatement pst = conn.prepareStatement("INSERT INTO IDENTITAS (ID_Guru, Nama, Mata_Pelajaran) VALUES(?,?,?)");
        pst.setString(1, ID_Guru);
        pst.setString(2, Nama);
        pst.setString(3, Mata_Pelajaran);
        return pst.executeUpdate();
    }

    private int perbaruiData(Connection conn, String ID_Guru, String Nama, String Mata_Pelajaran) throws SQLException {
        PreparedStatement pst = conn.prepareStatement("UPDATE IDENTITAS SET Nama = ? , Mata_Pelajaran = ? WHERE ID_Guru = ?");
        pst.setString(1, Nama);
        pst.setString(2, Mata_Pelajaran);
        pst.setString(3, ID_Guru);
        return pst.executeUpdate();
    }

    private int hapusData(Connection conn, String ID_Guru) throws SQLException {
        PreparedStatement pst = conn.prepareStatement("DELETE FROM IDENTITAS WHERE ID_Guru = ?");
        pst.setString(1, ID_Guru);
        return pst.executeUpdate();
    }

    private void tampil(Connection conn) {
        dataGuru.clear();
        try {
            String sql = "select * from IDENTITAS";
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                Guru data = new Guru();
                data.setID_Guru(String.valueOf(rs.getObject(1)));
                data.setNama(String.valueOf(rs.getObject(2)));
                data.setMata_Pelajaran(String.valueOf(rs.getObject(3)));
                dataGuru.add(data);
            }
            DefaultTableModel model = (DefaultTableModel) jTableGuru.getModel();
            model.setRowCount(0);
            for (Guru data : dataGuru) {

                Object[] baris = new Object[3];
                baris[0] = data.getID_Guru();
                baris[1] = data.getNama();
                baris[2] = data.getMata_Pelajaran();

                model.addRow(baris);
            }
        } catch (SQLException ex) {
            Logger.getLogger(TampilanGUIku.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * Creates new form TampilanGUI
     */
    /**
     * Creates new form DatabaseGUI
     */
    public TampilanGUIku() {
        try {
            dataGuru = new ArrayList<>();
            initComponents();
            Connection conn = DriverManager.getConnection("jdbc:postgresql://localhost:5432/Guru", "postgres", "5432");
            tampil(conn);
        } catch (SQLException ex) {
            Logger.getLogger(TampilanGUIku.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelNama = new javax.swing.JLabel();
        jLabelID_Guru = new javax.swing.JLabel();
        jTextFieldID_Guru = new javax.swing.JTextField();
        jTextFieldNama = new javax.swing.JTextField();
        jButtonSimpan = new javax.swing.JButton();
        jButtonUpdate = new javax.swing.JButton();
        jButtonHapus = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableGuru = new javax.swing.JTable();
        jLabelMataPelajaran = new javax.swing.JLabel();
        jTextFieldMata_Pelajaran = new javax.swing.JTextField();
        jButtonCetak = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabelID_Guru1 = new javax.swing.JLabel();
        jLabelID_Guru2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabelNama.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabelNama.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNama.setText("Nama");
        jLabelNama.setToolTipText("");
        getContentPane().add(jLabelNama);
        jLabelNama.setBounds(110, 210, 150, 32);

        jLabelID_Guru.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabelID_Guru.setForeground(new java.awt.Color(255, 255, 255));
        jLabelID_Guru.setText("ID Guru");
        getContentPane().add(jLabelID_Guru);
        jLabelID_Guru.setBounds(110, 120, 110, 30);

        jTextFieldID_Guru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldID_GuruActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldID_Guru);
        jTextFieldID_Guru.setBounds(330, 120, 210, 30);

        jTextFieldNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNamaActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldNama);
        jTextFieldNama.setBounds(330, 210, 210, 30);

        jButtonSimpan.setBackground(new java.awt.Color(255, 153, 0));
        jButtonSimpan.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonSimpan.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSimpan.setText("Simpan");
        jButtonSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSimpanActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSimpan);
        jButtonSimpan.setBounds(110, 400, 110, 40);

        jButtonUpdate.setBackground(new java.awt.Color(255, 153, 0));
        jButtonUpdate.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonUpdate.setForeground(new java.awt.Color(255, 255, 255));
        jButtonUpdate.setText("Update");
        jButtonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonUpdate);
        jButtonUpdate.setBounds(290, 400, 110, 40);

        jButtonHapus.setBackground(new java.awt.Color(255, 153, 0));
        jButtonHapus.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonHapus.setForeground(new java.awt.Color(255, 255, 255));
        jButtonHapus.setText("Hapus");
        jButtonHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHapusActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonHapus);
        jButtonHapus.setBounds(470, 400, 110, 40);

        jScrollPane2.setBackground(new java.awt.Color(153, 153, 153));

        jTableGuru.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID Guru", "Nama", "Mata Pelajaran"
            }
        ));
        jTableGuru.setGridColor(new java.awt.Color(51, 51, 255));
        jTableGuru.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableGuruMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableGuru);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(650, 110, 410, 230);

        jLabelMataPelajaran.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabelMataPelajaran.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMataPelajaran.setText("Mata Pelajaran");
        getContentPane().add(jLabelMataPelajaran);
        jLabelMataPelajaran.setBounds(110, 300, 180, 30);

        jTextFieldMata_Pelajaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMata_PelajaranActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldMata_Pelajaran);
        jTextFieldMata_Pelajaran.setBounds(330, 300, 210, 30);

        jButtonCetak.setBackground(new java.awt.Color(255, 153, 0));
        jButtonCetak.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonCetak.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCetak.setText("Cetak");
        jButtonCetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCetakActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCetak);
        jButtonCetak.setBounds(690, 400, 290, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\ASUS\\Downloads\\background kelas4.jpeg")); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -70, 1450, 830);

        jLabelID_Guru1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelID_Guru1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelID_Guru1.setText("ID Guru");
        getContentPane().add(jLabelID_Guru1);
        jLabelID_Guru1.setBounds(110, 120, 73, 25);

        jLabelID_Guru2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelID_Guru2.setForeground(new java.awt.Color(255, 255, 255));
        jLabelID_Guru2.setText("ID Guru");
        getContentPane().add(jLabelID_Guru2);
        jLabelID_Guru2.setBounds(100, 130, 73, 25);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldID_GuruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldID_GuruActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldID_GuruActionPerformed

    private void jTextFieldNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNamaActionPerformed

    private void jButtonSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSimpanActionPerformed
        String ID_Guru = jTextFieldID_Guru.getText().trim();
        String Nama = jTextFieldNama.getText();
        String Mata_Pelajaran = jTextFieldMata_Pelajaran.getText();
        if (!ID_Guru.isEmpty() && !Nama.isEmpty() && !Mata_Pelajaran.isEmpty()) {
            try {
                // TODO add your handling code here:
                Connection conn = DriverManager.getConnection("jdbc:postgresql://localhost:5432/Guru", "postgres", "5432");
                int k = masukkanData(conn, ID_Guru, Nama, Mata_Pelajaran);
                if (k > 0) {
                    tampil(conn);
                    this.peringatan("Simpan Berhasil");
                } else {
                    this.peringatan("Simpan Gagal");
                }
            } catch (SQLException ex) {
                Logger.getLogger(TampilanGUIku.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            this.peringatan("Input Data Guru Gagal");
        }
        jTextFieldID_Guru.setText("");
        jTextFieldNama.setText("");
        jTextFieldMata_Pelajaran.setText("");
    }//GEN-LAST:event_jButtonSimpanActionPerformed

    private void jButtonHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHapusActionPerformed
        // TODO add your handling code here:

        String ID_Guru = jTextFieldID_Guru.getText().trim();
        if (!ID_Guru.isEmpty()) {
            try {
                Connection conn = DriverManager.getConnection("jdbc:postgresql://localhost:5432/Guru", "postgres", "5432");

                // Hapus data dengan ID_Guru tertentu
                int k = hapusData(conn, ID_Guru);

                if (k > 0) {
                    tampil(conn);
                    this.peringatan("Hapus Berhasil");
                } else {
                    this.peringatan("Hapus Gagal: Data tidak ditemukan");
                }
            } catch (SQLException ex) {
                Logger.getLogger(TampilanGUIku.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            this.peringatan("Input ID_Guru untuk Hapus Data");
        }
        jTextFieldID_Guru.setText("");
        jTextFieldNama.setText("");
        jTextFieldMata_Pelajaran.setText("");


    }//GEN-LAST:event_jButtonHapusActionPerformed

    private void jButtonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateActionPerformed
        // TODO add your handling code here:private void jButtonSimpanActionPerformed(java.awt.event.ActionEvent evt) {                                              
        String ID_Guru = jTextFieldID_Guru.getText().trim();
        String Nama = jTextFieldNama.getText();
        String Mata_Pelajaran = jTextFieldMata_Pelajaran.getText();
        if (!ID_Guru.isEmpty() && !Nama.isEmpty() && !Mata_Pelajaran.isEmpty()) {
            try {
                Connection conn = DriverManager.getConnection("jdbc:postgresql://localhost:5432/Guru", "postgres", "5432");
                // Perbarui data jika data dengan NIM tertentu sudah ada
                int k = perbaruiData(conn, ID_Guru, Nama, Mata_Pelajaran);
                if (k > 0) {
                    tampil(conn);
                    this.peringatan("Update Berhasil");
                } else {
                    // Jika perbaruiData tidak berhasil, coba masukkan sebagai data baru
                    this.peringatan("Update Gagal");
                }
            } catch (SQLException ex) {
                Logger.getLogger(TampilanGUIku.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            this.peringatan("Input Data Guru Gagal");
        }
        jTextFieldID_Guru.setText("");
        jTextFieldNama.setText("");
        jTextFieldMata_Pelajaran.setText("");


    }//GEN-LAST:event_jButtonUpdateActionPerformed

    private void jTextFieldMata_PelajaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMata_PelajaranActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMata_PelajaranActionPerformed

    private void jTableGuruMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableGuruMouseClicked
        // TODO add your handling code here:
        int baris = jTableGuru.rowAtPoint(evt.getPoint());

        String ID_Guru = jTableGuru.getValueAt(baris, 0).toString();
        jTextFieldID_Guru.setText(ID_Guru);

        String Nama = jTableGuru.getValueAt(baris, 1).toString();
        jTextFieldNama.setText(Nama);

        String Mata_Pelajaran = jTableGuru.getValueAt(baris, 2).toString();
        jTextFieldMata_Pelajaran.setText(Mata_Pelajaran);
    }//GEN-LAST:event_jTableGuruMouseClicked

    private void jButtonCetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCetakActionPerformed
        // TODO add your handling code here:
           try {
            // TODO add your handling code here:
            Connection conn = DriverManager.getConnection("jdbc:postgresql://localhost:5432/Guru", "postgres", "5432");

            //File jasperFile = new File("src/pbopertemuan6/mahasiswa.jasper");
            // JasperPrint jp = JasperFillManager.fillReport(jasperFile.getPath(), null, conn);
            String jrxmlFile = new String("src/tampilandatabase/report1Guru.jrxml");
            JasperReport jr = JasperCompileManager.compileReport(jrxmlFile);
            JasperPrint jp = JasperFillManager.fillReport(jr, null, conn);
            JasperViewer.viewReport(jp, false);
        } catch (JRException ex) {
            Logger.getLogger(TampilanGUIku.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(TampilanGUIku.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonCetakActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TampilanGUIku.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TampilanGUIku.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TampilanGUIku.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TampilanGUIku.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TampilanGUIku().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCetak;
    private javax.swing.JButton jButtonHapus;
    private javax.swing.JButton jButtonSimpan;
    private javax.swing.JButton jButtonUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelID_Guru;
    private javax.swing.JLabel jLabelID_Guru1;
    private javax.swing.JLabel jLabelID_Guru2;
    private javax.swing.JLabel jLabelMataPelajaran;
    private javax.swing.JLabel jLabelNama;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableGuru;
    private javax.swing.JTextField jTextFieldID_Guru;
    private javax.swing.JTextField jTextFieldMata_Pelajaran;
    private javax.swing.JTextField jTextFieldNama;
    // End of variables declaration//GEN-END:variables
}
